site_name: NVIDIA GitHub Action Runners
site_url: https://docs.gha-runners.nvidia.com/
site_description: >-
  Documentation about using and setting up NVIDIA's self-hosted runners
  for GitHub Actions.
repo_name: nv-gha-runners/docs
repo_url: https://github.com/nv-gha-runners/docs
copyright: Copyright &copy; 2023 NVIDIA Corporation
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home:
      - index.md
      - Onboarding:
          - onboarding/index.md
          - NVIDIA Orgs: onboarding/nvidia.md
  - GitHub Applications:
      - apps/index.md
      - Copy PR Bot:
          - apps/copy-pr-bot/index.md
          - FAQs: apps/copy-pr-bot/faqs.md
      - NVIDIA Runner Mgmt:
          - apps/nvidia-runner-mgmt/index.md
  - Runners:
      - runners/index.md
